name: resource
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  get_it: ^8.0.3
  slang: ^4.4.1
  logger: ^2.5.0
  go_router: ^14.6.3
  slang_flutter: ^4.4.0
  rxdart: ^0.28.0
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  slang_build_runner: ^4.4.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900

        - asset: assets/fonts/rubik_italic/Rubik-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/rubik_italic/Rubik-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/rubik_italic/Rubik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/rubik_italic/Rubik-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/rubik_italic/Rubik-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/rubik_italic/Rubik-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/rubik_italic/Rubik-BlackItalic.ttf
          style: italic
          weight: 900